name: Python Linting

on:
  push:
    branches-ignore: "main"
    paths:
      - "**/**.py"
  pull_request:
    branches-ignore: "main"
    paths:
      - "**/**.py"

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Get changed files
      id: files
      run: |
        echo "::set-output name=python_files::$(git fetch origin ${{ github.base_ref }} && git diff --name-only ${{ github.base_ref }} | grep '\.py$')"
    - name: Run Pylint on changed files
      run: |
        pylint ${{ steps.files.outputs.python_files }} --exit-zero
    - name: Fail if score is less than 10
      run: |
        score=$(pylint --output-format=text ${{ steps.files.outputs.python_files }} | sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p')
        echo "Pylint score: $score"
        if (( $(echo "$score < 10" | bc -l) )); then
          echo "Pylint score is less than 10, failing the workflow."
          exit 1
        fi
