name: Python Linting

on:
  push:
    branches-ignore: "main"
    paths:
      - "**/**.py"
  pull_request:
    branches-ignore: "main"
    paths:
      - "**/**.py"

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint
      run: |
        pylint $(find . -type f -name "*.py") --exit-zero

    - name: Check pylint score
      run: |
        score=$(pylint --output-format=text $(find . -type f -name "*.py") | sed -n 's/^Your code has been rated at \([-0-9.]*\)\/10.*/\1/p')
        echo "Pylint score: $score"
        if (( $(echo "$score < 8.0" | bc -l) )); then
          echo "Pylint score is less than 8.0, failing the check..."
          exit 1
        fi
