name: Python Linting

on:
  push:
    branches-ignore: "main"
    paths:
      - "**/**.py"
  pull_request:
    branches-ignore: "main"
    paths:
      - "**/**.py"

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc
        python -m pip install --upgrade pip
        pip install pylint

    - id: set-changed-files
      name: Get list of changed files
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
          echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | grep '\.py$') | xargs)" >> $GITHUB_OUTPUT
        else
          echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.py$') | xargs)" >> $GITHUB_OUTPUT
        fi

    - name: Run pylint on changed files
      run: |
        if [ -n "${{ steps.set-changed-files.outputs.changed-files }}" ]; then
          pylint ${{ steps.set-changed-files.outputs.changed-files }} --exit-zero
        else
          echo "No Python files to lint."
        fi

    - name: Check pylint score
      run: |
        if [ -n "${{ steps.set-changed-files.outputs.changed-files }}" ]; then
          score=$(pylint --output-format=text ${{ steps.set-changed-files.outputs.changed-files }} | sed -n 's/^Your code has been rated at \([-0-9.]*\)\/10.*/\1/p')
          echo "Pylint score: $score"
          if (( $(echo "$score < 8.0" | bc -l) )); then
            echo "Pylint score is less than 8.0, failing the check..."
            exit 1
          fi
        else
          echo "No Python files to lint, skipping score check."
        fi
